### ISSUE TITLE
ModuleNotFoundError: No module named 'gym_residual_fetch'

### ISSUE THREAD

**Issue by krishanrana** [k-r-allen/residual-policy-learning#10]
Hi, thank you for sorting out the download link issue. I have come across a new import error when running the bash script run_all_experiments.sh. Where would i be able to find these modules? It is an import within the config_standard_pickandplace.py file.

**Comment by k-r-allen** [comment]
Just to check, did you first install the environments with the commands below? 
cd rpl_environments
pip install -e .

**Comment by krishanrana** [comment]
Hi, yes I followed all the step as described in the README

**Comment by tomsilver** [comment]
Sorry, I think the README may be missing a step. Would you mind trying to do `pip install -e .` inside the subdirectories https://github.com/k-r-allen/residual-policy-learning/tree/master/gym-residual-fetch and https://github.com/k-r-allen/residual-policy-learning/tree/master/gym-residual-complex-objects ? That should make available `gym_residual_fetch` and `gym_residual_complex_objects`. (We will update the README if this indeed is the issue.) Thanks for your patience!

**Comment by krishanrana** [comment]
Thanks @tomsilver that did solve that issue however a new error is thrown regarding these. The error thrown is:     

raise error.Error('Cannot re-register id: {}'.format(id))
gym.error.Error: Cannot re-register id: ResidualFetchPickAndPlace-v0

**Comment by tomsilver** [comment]
Hi @krishanrana, sorry again -- I realized that my previous suggestion was wrong. We shouldn't have had those subdirectories in the repository in the first place and we shouldn't have been importing `gym_residual_fetch` anywhere. (These bugs were introduced when I was renaming things at the last minute.) I just committed changes that remove the imports to `gym_residual_fetch` and `gym_residual_complex_objects`. I also verified with a fresh install that the errors you were seeing are resolved and that things seem to run okay. But please let me know if you run into any more issues and thanks again for taking the time to try this all out.
